"""empty message

Revision ID: 1443878ad537
Revises: fbf690605397
Create Date: 2018-07-12 11:12:00.662930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1443878ad537'
down_revision = 'fbf690605397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agreement_notary_id_fkey', 'agreement', type_='foreignkey')
    op.drop_column('agreement', 'notary_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('notary_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('agreement_notary_id_fkey', 'agreement', 'user', ['notary_id'], ['id'])
    # ### end Alembic commands ###
