"""empty message

Revision ID: fbf690605397
Revises: 6835d8a56943
Create Date: 2018-07-12 10:49:44.569595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbf690605397'
down_revision = '6835d8a56943'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agreement', sa.Column('notary_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agreement', 'user', ['notary_id'], ['id'])
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.drop_constraint(None, 'agreement', type_='foreignkey')
    op.drop_column('agreement', 'notary_id')
    # ### end Alembic commands ###
